### ISSUE TITLE
Regression: moderncv sections are aligned to the left

### ISSUE THREAD

**Issue by orgads** [tex-xet/bidi#47]
I use the debian package of texlive-lang-arabic. Version 20161130 worked correctly, and version 20170118 is broken.

I use this document as an example: http://pastebin.com/tpSqv7re

This is how it used to look:
![Right alignment](https://ibin.co/3BXmRmBHhNNx.png)

And this is how it looks now:
![Wrong alignment](https://ibin.co/3BXmXhyRRZ7h.png)

**Comment by vafa** [comment]
I am afraid that this has nothing to do with the `bidi` package. The `bidi` package does absolutely no change to the `moderncv` class so you should report it to the author of `moderncv`.

Please note that the `bidi` package provides a variation of `moderncv` class (`bidimoderncv`) and there should be few examples in the documentation directory.

**Comment by orgads** [comment]
I tested it by replacing *only* texlive-lang-arabic, which obviously doesn't contain moderncv. With the previous version it works, with the current one it doesn't.

**Comment by vafa** [comment]
I doubt that this has anything to do with the `bidi` package but I will have a look at it later today.

**Comment by vafa** [comment]
I have had no luck processing your file with `xelatex` as it gives me several errors. There are two issues both related to the package `hyperref`:

1. The class `moderncv` loads `hyperref` and your minimal example loads `hyperref` too so there is a clash option with the `hyperref` package;

2. The package `bidi` expects to be the last loaded package while `moderncv` loads package `hyperref` very late in the preamble so `hyperref` will be loaded after `bidi` package and this gives an error since `bidi` can not let any other package be loaded after itself.

I am using an updated version of TeXLive 2016. Your minimal example can be modified as follow to run smoothly with my TeX distribution.

````latex
\RequirePackage{biditools}
\makeatletter
\bidi@BeforePackage{hyperref}{\let\orig@maketitle\maketitle}
\bidi@AfterAtEndOfPackage{hyperref}{\let\maketitle\orig@maketitle\usepackage[RTLdocument]{bidi}}
\makeatother
\documentclass{moderncv}
\moderncvtheme[blue]{classic}
\usepackage{fontspec}
\usepackage[scale=0.82]{geometry}

 
\AtBeginDocument{\setlength{\makecvheadnamewidth}{8cm}}
\AtBeginDocument{\recomputelengths}
\renewcommand*{\emailsymbol}{\marvosymbol{64}~}
\renewcommand*{\addresssymbol}{\marvosymbol{66}~}
 
\setmainfont{DejaVu Sans}
\firstname{ישראל}
\familyname{ישראלי}
\address{ישראל}{}
 
\begin{document}
\makecvtitle
\vspace*{-3em}
 
\section{לימודים}
\cventry{2012-2015}{בלה}{בלה בלה}{בלה}{}{בלה בלה בלה}
 
\end{document}
````
It still has the issue you mentioned but it has nothing to do with the `bidi` package and I am unlikely to support the `moderncv` class in the `bidi` package as the `bidi` package provides the `bidimoderncv` class. If you want bidi support with `moderncv`, use `bidimodercv` class.

**Comment by orgads** [comment]
But did you test if the bug existed with 20161130? Because it used to work.

**Comment by vafa** [comment]
That versioning is meaningless; sorry! What version of the `bidi` package are we taking about? between what versions of the `bidi` package the behavior changes?

**Comment by vafa** [comment]
If you look at [TeXlive repository](http://tug.org/svn/texlive/trunk/Master/texmf-dist/source/xelatex/bidi/bidi.dtx?view=log), you can see the dates of the different commits for the `bidi` package. So perhaps you are taking about [bidi (30nov16)](http://tug.org/svn/texlive/trunk/Master/texmf-dist/source/xelatex/bidi/bidi.dtx?revision=42611&view=co) and [bidi (16jan17)](http://tug.org/svn/texlive/trunk/Master/texmf-dist/source/xelatex/bidi/bidi.dtx?revision=42967&view=co). The change between two versions can be seen [here](http://tug.org/svn/texlive/trunk/Master/texmf-dist/source/xelatex/bidi/bidi.dtx?r1=42611&r2=42967). I do not see a single change which would account for the behavior you claim.

**Comment by vafa** [comment]
I now accept donations to the bidi package. Anyone can donate any amount to the bidi package using [My PayPal.Me](https://www.paypal.me/persiantex).

The donations allow me to spend more time working on the bidi package and make it even better. If you know that some other people may also be interested in donating to the bidi package development, please let them know.
