### ISSUE TITLE
\LTRcite error

### ISSUE THREAD

**Issue by mhmd0123** [tex-xet/bidi#58]
When I use `neveshtuft` class, I get this error:
`! Undefined control sequence.
 <argument> ...@biditufteLTRsidenote@citation@font 
                                                   \setcounter {@bidituftesid...
 l.5 \LTRcite{george95}      
 ? `

It seems there is a problem with `\LTRcite' but I don't know how to figure it out. I've attached a sample file and its log.

[helpme.zip](https://github.com/tex-xet/bidi/files/1248601/helpme.zip)

**Comment by vafa** [comment]
The `neveshtuft` is itself based on the `biditufte` bundle which uses `natbib` package while `\LTRcite` has no `natbib` compatible version. So the question really is 

> If I am willing to implement it?

I do not have an answer right know but I will keep this issue open.

Note that you are more than welcome to donate some funds to the project so that I can have some spare time for development.

**Comment by mhmd0123** [comment]
@vafa Thanks. I followed that link and found `@biditufteLTRsidenote@citation@font` must be changed to `@bidituftesidenote@LTRcitation@font` in configuration file.
